name = "hugo-console-goakshit"
license = "MIT"
licenselink = "https://github.com/goakshit/hugo-theme-console/blob/master/LICENSE"
description = "A minimal, responsive and light theme for Hugo inspired by Linux console."
homepage = "https://github.com/goakshit/hugo-theme-console"
tags = ["blog", "gallery", "portfolio", "console", "terminal", "clean", "personal", "minimal", "monotone", "simple", "technical", "responsive", "mobile", "minimalist", "retro", "animation"]
features = ["disqus", "responsive", "google analytics"]
min_version = "0.69.0"

[original]
    name = "Marcin Mierzejewski"
    homepage = "https://mrmierzejewski.com"
    github = "https://github.com/mrmierzejewski"

[author]
    author = "Akshit Dhar"
    homepage = ""
    github = "https://github.com/goakshit"
